feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

server:
  port: 8080


logging:
  level:
    br.com.wine.service.customer.controllers.CustomerClient: debug